#!/bin/bash
# Setup local access to Railway PostgreSQL database

echo "=== Railway Database Local Access Setup ==="
echo ""
echo "Option 1: Using Railway CLI"
echo "----------------------------"
echo "1. Install Railway CLI:"
echo "   npm install -g @railway/cli"
echo ""
echo "2. Login to Railway:"
echo "   railway login"
echo ""
echo "3. Link your project:"
echo "   railway link"
echo ""
echo "4. Connect to PostgreSQL:"
echo "   railway run psql"
echo ""
echo "5. Then run the diagnostic query:"
echo "   \\i scripts/check-duplicate-amounts.sql"
echo ""
echo "Option 2: Direct PostgreSQL Connection"
echo "--------------------------------------"
echo "1. Get DATABASE_URL from Railway dashboard:"
echo "   - Go to Railway → Backend service → Variables"
echo "   - Copy DATABASE_URL value"
echo ""
echo "2. Connect using psql:"
echo "   psql 'postgresql://user:pass@host:port/db'"
echo ""
echo "3. Or connect using any PostgreSQL client (DBeaver, pgAdmin, etc.)"
echo ""
echo "Option 3: Railway CLI Inline Command"
echo "-----------------------------------"
echo "Run SQL directly:"
echo "   railway run psql -c \"SELECT COUNT(*) FROM pending_duplicates WHERE (newTransactionData->>'amount' IS NULL);\""
echo ""
